version: '3'

services:
  worker-trheads-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/code
    command: npm run start
